@HostAddress = http://localhost:5000

POST {{HostAddress}}/
Accept: application/json, text/event-stream
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
        "clientInfo": {
            "name": "RestClient",
            "version": "0.1.0"
        },
        "capabilities": {},
        "protocolVersion": "2025-11-25"
    }
}

###

@SessionId = W2Yac74zzEqW7zCvR7VC9g

POST {{HostAddress}}/
Accept: application/json, text/event-stream
Content-Type: application/json
MCP-Protocol-Version: 2025-11-25
Mcp-Session-Id: {{SessionId}}

{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "tools/list"
}

###

POST {{HostAddress}}/
Accept: application/json, text/event-stream
Content-Type: application/json
MCP-Protocol-Version: 2025-11-25
Mcp-Session-Id: {{SessionId}}

{
    "jsonrpc": "2.0",
    "id": 3,
    "method": "tools/call",
    "params": {
        "name": "weather_forecast",
        "arguments": {
            "cityState": "Austin, TX"
        }
    }
}
